//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDD_DIALOG1                     101
#define IDD_LOGINDIALOG                 101
#define IDD_CREATEACCOUNT               103
#define IDD_LOBBYDIALOG                 104
#define IDD_CREATEGAME                  105
#define IDD_CREATEVIEWPLAYERS           106
#define IDD_JOINVIEWPLAYERS             107
#define IDC_NEWACCOUNT                  1000
#define IDC_LOGIN_CREATEACCOUNT         1000
#define IDC_LOGIN                       1001
#define IDC_DOLOGIN                     1001
#define IDC_QUIT                        1002
#define IDC_LOGIN_QUIT                  1002
#define IDC_LOGIN_NICKNAME              1003
#define IDC_LOGIN_PASSWORD              1004
#define IDC_LOGIN_IPADDRESS             1005
#define IDC_CREATEACCOUNT_AGE           1007
#define IDC_CREATEACCOUNT_NICKNAME      1008
#define IDC_CREATEACCOUNT_FIRSTNAME     1009
#define IDC_CREATEACCOUNT_SURNAME       1010
#define IDC_CREATEACCOUNT_CANCEL        1011
#define IDC_CREATEACCOUNT_CONTINUE      1012
#define IDC_CREATEACCOUNT_GENDER        1013
#define IDC_CREATEACCOUNT_PASSWORD1     1014
#define IDC_CREATEACCOUNT_PASSWORD2     1015
#define IDC_CREATEACCOUNT_IPADDRESS     1016
#define IDC_CREATEACCOUNT_EMAIL         1017
#define IDC_CHATMESSAGE                 1017
#define IDC_SENDCHATMESSAGE             1018
#define IDC_CHATLIST                    1019
#define IDC_CREATEGAME                  1020
#define IDC_JOINGAME                    1021
#define IDC_GAMELIST                    1022
#define IDC_LOGOUT                      1023
#define IDC_PLAYERLIST                  1025
#define IDC_GAMENAME                    1027
#define IDC_DOCREATEGAME                1028
#define IDC_CANCELCREATEGAME            1029
#define IDC_PLAYERSINGAME               1030
#define IDC_CANCELGAME                  1031
#define IDC_STARTGAME                   1032
#define IDC_JOINCANCEL                  1033
#define IDC_JOINPLAYERSINGAME           1034

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
